### ISSUE TITLE
EOFError test fails on JRuby

### ISSUE THREAD

**Issue by davidor** [socketry/async-redis#13]
There's one test that fails under JRuby: `Async::Redis::Client should raise EOFError on unexpected disconnect`. See the Travis job for PR #11 https://travis-ci.org/socketry/async-redis/jobs/501174074

**Comment by ioquatix** [comment]
I think we are hitting a bug on our end because we are closing the socket twice.

```ruby
				stream = Async::IO::Stream.new(connection)
				stream.read(8)
				stream.close
				connection.close
```

`stream.close` also closes the underlying connection.

Can you try removing `connection.close`? I think it should fix the test failure.

**Comment by ioquatix** [comment]
https://github.com/socketry/async-io/blob/master/lib/async/io/stream.rb#L166-L178

**Comment by davidor** [comment]
You're right, that `connection.close` should not be necessary. However, deleting that call does not fix the issue: https://github.com/socketry/async-redis/pull/14

**Comment by ioquatix** [comment]
Fixed.
